FROM hivesolutions/alpine:latest
MAINTAINER Hive Solutions

EXPOSE 67/udp

ADD dhcp /etc/dhcp_registers

RUN apk update && apk add dhcp
RUN touch /var/lib/dhcp/dhcpd.leases

CMD ["/usr/sbin/dhcpd", "-f", "-cf", "/etc/dhcp_registers/dhcpd.conf"]
