FROM hivesolutions/python:latest

LABEL maintainer="Hive Solutions <development@hive.pt>"

ENV HOME /

ADD colony.json /colony.json

RUN pip3 install netius hpack colony
RUN cpm install omni_assets
RUN wget https://github.com/hivesolutions/config/raw/master/omni/proxy.py

ENTRYPOINT ["/usr/bin/python3", "/proxy.py"]
