FROM hivesolutions/pypy:latest
MAINTAINER Hive Solutions

ENV HOME /

ADD colony.json /colony.json

RUN pip install netius hpack colony
RUN cpm install omni_assets
RUN wget https://github.com/hivesolutions/config/raw/master/omni/proxy.py

ENTRYPOINT ["/usr/bin/python", "/proxy.py"]
