FROM hivesolutions/pypy:latest

LABEL version="1.0"
LABEL maintainer="Hive Solutions <development@hive.pt>"

ENV HOME /

ADD colony.json /colony.json

RUN pip install "netius<1.17.0" hpack colony
RUN cpm install omni_assets
RUN wget https://github.com/hivesolutions/config/raw/master/omni/proxy.py

ENTRYPOINT ["/usr/bin/python", "/proxy.py"]
