#!/bin/bash
# -*- coding: utf-8 -*-

if [ ! -L /data/mysql ]; then

    if [ ! -d /data/mysql ]; then
        mkdir -p /data/mysql
        chown mysql:mysql /data/mysql
        cp -rp /var/lib/mysql/* /data/mysql
    fi

    rm -rf /var/lib/mysql
    ln -s /data/mysql /var/lib/mysql

fi

trap 'kill -s SIGTERM $PID; for child in $(ps -o pid= --ppid $PID); do kill -s SIGTERM $child; done; wait $PID' TERM INT
/usr/bin/mysqld_safe "$@" &
PID=$!
wait $PID
exit $?
