#!/bin/bash
# -*- coding: utf-8 -*-

if [ ! -L /data/redis ]; then

    if [ ! -d /data/redis ]; then  
        mkdir /data/redis
    fi

    rm -rf /var/lib/redis
    ln -s /data/redis /var/lib/redis

fi

exec /usr/bin/redis-server "$@"
exit $?
