#!/bin/bash
# -*- coding: utf-8 -*-

if [ ! -L /data/redis ]; then

    if [ ! -d /data/redis ]; then
        mkdir /data/redis
    fi

    rm -rf /var/lib/redis
    ln -s /data/redis /var/lib/redis

fi

trap 'kill -s SIGTERM $PID; for child in $(ps -o pid= --ppid $PID); do kill -s SIGTERM $child; done; wait $PID' TERM INT
/usr/bin/redis-server "$@"
PID=$!
wait $PID
exit $?
