#!/bin/bash
# -*- coding: utf-8 -*-

if [ ! -L /data/redis ]; then

    if [ ! -d /data/redis ]; then  
        mkdir /data/redis
        if [ -d //var/lib/redis ]; then
            cp -rp /var/lib/redis/* /data/redis
        fi
    fi

    rm -rf /var/lib/redis
    ln -s /data/redis /var/lib/redis

fi

/usr/bin/redis-server "$@"
